/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CameraModeData {
  'wideSettings' : WideSettings,
  'fieldOfView' : bigint,
  'standardSettings' : StandardSettings,
  'activeMode' : CameraModeType,
}
export type CameraModeType = { 'wide' : null } |
  { 'standard' : null };
export type ExternalBlob = Uint8Array;
export type ProcessingStatus = {
    'completed' : { 'result' : VideoAnalysisResult }
  } |
  { 'uploading' : { 'progress' : bigint } } |
  { 'processing' : null } |
  { 'failed' : { 'error' : string } };
export interface StandardSettings {
  'stabilization' : boolean,
  'frameRate' : bigint,
  'resolution' : [bigint, bigint],
  'aspectRatio' : [bigint, bigint],
}
export interface TrajectoryFrame { 'ballPosition' : [number, number] }
export interface Verdict {
  'text' : string,
  'reasoning' : string,
  'confidence' : number,
}
export interface VideoAnalysisResult {
  'edgeDetection' : Verdict,
  'frameData' : Array<TrajectoryFrame>,
  'snickoOverlay' : Uint8Array,
  'trajectoryOverlay' : Uint8Array,
  'noBallDecision' : Verdict,
  'lbwDecision' : Verdict,
}
export interface VideoUpload {
  'id' : string,
  'analysisResult' : [] | [VideoAnalysisResult],
  'processingStatus' : ProcessingStatus,
  'videoBlob' : ExternalBlob,
  'cameraMode' : CameraModeData,
}
export interface WideSettings {
  'stabilization' : boolean,
  'frameRate' : bigint,
  'lensCorrection' : boolean,
  'resolution' : [bigint, bigint],
  'wideAngleMultiplier' : number,
  'aspectRatio' : [bigint, bigint],
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'deleteVideo' : ActorMethod<[string], string>,
  'filterVideosByMode' : ActorMethod<[CameraModeType], Array<VideoUpload>>,
  'getAllVideos' : ActorMethod<[], Array<VideoUpload>>,
  'getAnalysisResult' : ActorMethod<[string], [] | [VideoAnalysisResult]>,
  'getCameraMode' : ActorMethod<[string], [] | [CameraModeData]>,
  'getVideoStatus' : ActorMethod<[string], [] | [ProcessingStatus]>,
  'storeAnalysisResult' : ActorMethod<[string, VideoAnalysisResult], string>,
  'updateCameraMode' : ActorMethod<[string, CameraModeData], string>,
  'uploadVideo' : ActorMethod<[string, ExternalBlob], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];