/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const CameraModeType = IDL.Variant({
  'wide' : IDL.Null,
  'standard' : IDL.Null,
});
export const Verdict = IDL.Record({
  'text' : IDL.Text,
  'reasoning' : IDL.Text,
  'confidence' : IDL.Float64,
});
export const TrajectoryFrame = IDL.Record({
  'ballPosition' : IDL.Tuple(IDL.Float64, IDL.Float64),
});
export const VideoAnalysisResult = IDL.Record({
  'edgeDetection' : Verdict,
  'frameData' : IDL.Vec(TrajectoryFrame),
  'snickoOverlay' : IDL.Vec(IDL.Nat8),
  'trajectoryOverlay' : IDL.Vec(IDL.Nat8),
  'noBallDecision' : Verdict,
  'lbwDecision' : Verdict,
});
export const ProcessingStatus = IDL.Variant({
  'completed' : IDL.Record({ 'result' : VideoAnalysisResult }),
  'uploading' : IDL.Record({ 'progress' : IDL.Nat }),
  'processing' : IDL.Null,
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const WideSettings = IDL.Record({
  'stabilization' : IDL.Bool,
  'frameRate' : IDL.Nat,
  'lensCorrection' : IDL.Bool,
  'resolution' : IDL.Tuple(IDL.Nat, IDL.Nat),
  'wideAngleMultiplier' : IDL.Float64,
  'aspectRatio' : IDL.Tuple(IDL.Nat, IDL.Nat),
});
export const StandardSettings = IDL.Record({
  'stabilization' : IDL.Bool,
  'frameRate' : IDL.Nat,
  'resolution' : IDL.Tuple(IDL.Nat, IDL.Nat),
  'aspectRatio' : IDL.Tuple(IDL.Nat, IDL.Nat),
});
export const CameraModeData = IDL.Record({
  'wideSettings' : WideSettings,
  'fieldOfView' : IDL.Nat,
  'standardSettings' : StandardSettings,
  'activeMode' : CameraModeType,
});
export const VideoUpload = IDL.Record({
  'id' : IDL.Text,
  'analysisResult' : IDL.Opt(VideoAnalysisResult),
  'processingStatus' : ProcessingStatus,
  'videoBlob' : ExternalBlob,
  'cameraMode' : CameraModeData,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'deleteVideo' : IDL.Func([IDL.Text], [IDL.Text], []),
  'filterVideosByMode' : IDL.Func(
      [CameraModeType],
      [IDL.Vec(VideoUpload)],
      ['query'],
    ),
  'getAllVideos' : IDL.Func([], [IDL.Vec(VideoUpload)], ['query']),
  'getAnalysisResult' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(VideoAnalysisResult)],
      ['query'],
    ),
  'getCameraMode' : IDL.Func([IDL.Text], [IDL.Opt(CameraModeData)], ['query']),
  'getVideoStatus' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(ProcessingStatus)],
      ['query'],
    ),
  'storeAnalysisResult' : IDL.Func(
      [IDL.Text, VideoAnalysisResult],
      [IDL.Text],
      [],
    ),
  'updateCameraMode' : IDL.Func([IDL.Text, CameraModeData], [IDL.Text], []),
  'uploadVideo' : IDL.Func([IDL.Text, ExternalBlob], [IDL.Text], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const CameraModeType = IDL.Variant({
    'wide' : IDL.Null,
    'standard' : IDL.Null,
  });
  const Verdict = IDL.Record({
    'text' : IDL.Text,
    'reasoning' : IDL.Text,
    'confidence' : IDL.Float64,
  });
  const TrajectoryFrame = IDL.Record({
    'ballPosition' : IDL.Tuple(IDL.Float64, IDL.Float64),
  });
  const VideoAnalysisResult = IDL.Record({
    'edgeDetection' : Verdict,
    'frameData' : IDL.Vec(TrajectoryFrame),
    'snickoOverlay' : IDL.Vec(IDL.Nat8),
    'trajectoryOverlay' : IDL.Vec(IDL.Nat8),
    'noBallDecision' : Verdict,
    'lbwDecision' : Verdict,
  });
  const ProcessingStatus = IDL.Variant({
    'completed' : IDL.Record({ 'result' : VideoAnalysisResult }),
    'uploading' : IDL.Record({ 'progress' : IDL.Nat }),
    'processing' : IDL.Null,
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const WideSettings = IDL.Record({
    'stabilization' : IDL.Bool,
    'frameRate' : IDL.Nat,
    'lensCorrection' : IDL.Bool,
    'resolution' : IDL.Tuple(IDL.Nat, IDL.Nat),
    'wideAngleMultiplier' : IDL.Float64,
    'aspectRatio' : IDL.Tuple(IDL.Nat, IDL.Nat),
  });
  const StandardSettings = IDL.Record({
    'stabilization' : IDL.Bool,
    'frameRate' : IDL.Nat,
    'resolution' : IDL.Tuple(IDL.Nat, IDL.Nat),
    'aspectRatio' : IDL.Tuple(IDL.Nat, IDL.Nat),
  });
  const CameraModeData = IDL.Record({
    'wideSettings' : WideSettings,
    'fieldOfView' : IDL.Nat,
    'standardSettings' : StandardSettings,
    'activeMode' : CameraModeType,
  });
  const VideoUpload = IDL.Record({
    'id' : IDL.Text,
    'analysisResult' : IDL.Opt(VideoAnalysisResult),
    'processingStatus' : ProcessingStatus,
    'videoBlob' : ExternalBlob,
    'cameraMode' : CameraModeData,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'deleteVideo' : IDL.Func([IDL.Text], [IDL.Text], []),
    'filterVideosByMode' : IDL.Func(
        [CameraModeType],
        [IDL.Vec(VideoUpload)],
        ['query'],
      ),
    'getAllVideos' : IDL.Func([], [IDL.Vec(VideoUpload)], ['query']),
    'getAnalysisResult' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(VideoAnalysisResult)],
        ['query'],
      ),
    'getCameraMode' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(CameraModeData)],
        ['query'],
      ),
    'getVideoStatus' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ProcessingStatus)],
        ['query'],
      ),
    'storeAnalysisResult' : IDL.Func(
        [IDL.Text, VideoAnalysisResult],
        [IDL.Text],
        [],
      ),
    'updateCameraMode' : IDL.Func([IDL.Text, CameraModeData], [IDL.Text], []),
    'uploadVideo' : IDL.Func([IDL.Text, ExternalBlob], [IDL.Text], []),
  });
};

export const init = ({ IDL }) => { return []; };