/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface VideoAnalysisResult {
    edgeDetection: Verdict;
    frameData: Array<TrajectoryFrame>;
    snickoOverlay: Uint8Array;
    trajectoryOverlay: Uint8Array;
    noBallDecision: Verdict;
    lbwDecision: Verdict;
}
export interface WideSettings {
    stabilization: boolean;
    frameRate: bigint;
    lensCorrection: boolean;
    resolution: [bigint, bigint];
    wideAngleMultiplier: number;
    aspectRatio: [bigint, bigint];
}
export interface VideoUpload {
    id: string;
    analysisResult?: VideoAnalysisResult;
    processingStatus: ProcessingStatus;
    videoBlob: ExternalBlob;
    cameraMode: CameraModeData;
}
export interface StandardSettings {
    stabilization: boolean;
    frameRate: bigint;
    resolution: [bigint, bigint];
    aspectRatio: [bigint, bigint];
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface TrajectoryFrame {
    ballPosition: [number, number];
}
export interface CameraModeData {
    wideSettings: WideSettings;
    fieldOfView: bigint;
    standardSettings: StandardSettings;
    activeMode: CameraModeType;
}
export interface Verdict {
    text: string;
    reasoning: string;
    confidence: number;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export type ProcessingStatus = {
    __kind__: "completed";
    completed: {
        result: VideoAnalysisResult;
    };
} | {
    __kind__: "uploading";
    uploading: {
        progress: bigint;
    };
} | {
    __kind__: "processing";
    processing: null;
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export enum CameraModeType {
    wide = "wide",
    standard = "standard"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    deleteVideo(videoId: string): Promise<string>;
    filterVideosByMode(mode: CameraModeType): Promise<Array<VideoUpload>>;
    getAllVideos(): Promise<Array<VideoUpload>>;
    getAnalysisResult(videoId: string): Promise<VideoAnalysisResult | null>;
    getCameraMode(videoId: string): Promise<CameraModeData | null>;
    getVideoStatus(videoId: string): Promise<ProcessingStatus | null>;
    storeAnalysisResult(videoId: string, result: VideoAnalysisResult): Promise<string>;
    updateCameraMode(videoId: string, newMode: CameraModeData): Promise<string>;
    uploadVideo(id: string, videoBlob: ExternalBlob): Promise<string>;
}
import type { CameraModeData as _CameraModeData, CameraModeType as _CameraModeType, ExternalBlob as _ExternalBlob, ProcessingStatus as _ProcessingStatus, StandardSettings as _StandardSettings, VideoAnalysisResult as _VideoAnalysisResult, VideoUpload as _VideoUpload, WideSettings as _WideSettings, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async deleteVideo(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteVideo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteVideo(arg0);
            return result;
        }
    }
    async filterVideosByMode(arg0: CameraModeType): Promise<Array<VideoUpload>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterVideosByMode(to_candid_CameraModeType_n8(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterVideosByMode(to_candid_CameraModeType_n8(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllVideos(): Promise<Array<VideoUpload>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllVideos();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllVideos();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAnalysisResult(arg0: string): Promise<VideoAnalysisResult | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnalysisResult(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnalysisResult(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCameraMode(arg0: string): Promise<CameraModeData | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCameraMode(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCameraMode(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVideoStatus(arg0: string): Promise<ProcessingStatus | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getVideoStatus(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVideoStatus(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async storeAnalysisResult(arg0: string, arg1: VideoAnalysisResult): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.storeAnalysisResult(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.storeAnalysisResult(arg0, arg1);
            return result;
        }
    }
    async updateCameraMode(arg0: string, arg1: CameraModeData): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCameraMode(arg0, to_candid_CameraModeData_n23(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCameraMode(arg0, to_candid_CameraModeData_n23(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async uploadVideo(arg0: string, arg1: ExternalBlob): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadVideo(arg0, await to_candid_ExternalBlob_n25(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadVideo(arg0, await to_candid_ExternalBlob_n25(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_CameraModeData_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CameraModeData): CameraModeData {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_CameraModeType_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CameraModeType): CameraModeType {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_ProcessingStatus_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProcessingStatus): ProcessingStatus {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
async function from_candid_VideoUpload_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VideoUpload): Promise<VideoUpload> {
    return await from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_VideoAnalysisResult]): VideoAnalysisResult | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CameraModeData]): CameraModeData | null {
    return value.length === 0 ? null : from_candid_CameraModeData_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ProcessingStatus]): ProcessingStatus | null {
    return value.length === 0 ? null : from_candid_ProcessingStatus_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    analysisResult: [] | [_VideoAnalysisResult];
    processingStatus: _ProcessingStatus;
    videoBlob: _ExternalBlob;
    cameraMode: _CameraModeData;
}): Promise<{
    id: string;
    analysisResult?: VideoAnalysisResult;
    processingStatus: ProcessingStatus;
    videoBlob: ExternalBlob;
    cameraMode: CameraModeData;
}> {
    return {
        id: value.id,
        analysisResult: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.analysisResult)),
        processingStatus: from_candid_ProcessingStatus_n14(_uploadFile, _downloadFile, value.processingStatus),
        videoBlob: await from_candid_ExternalBlob_n16(_uploadFile, _downloadFile, value.videoBlob),
        cameraMode: from_candid_CameraModeData_n17(_uploadFile, _downloadFile, value.cameraMode)
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    wideSettings: _WideSettings;
    fieldOfView: bigint;
    standardSettings: _StandardSettings;
    activeMode: _CameraModeType;
}): {
    wideSettings: WideSettings;
    fieldOfView: bigint;
    standardSettings: StandardSettings;
    activeMode: CameraModeType;
} {
    return {
        wideSettings: value.wideSettings,
        fieldOfView: value.fieldOfView,
        standardSettings: value.standardSettings,
        activeMode: from_candid_CameraModeType_n19(_uploadFile, _downloadFile, value.activeMode)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        result: _VideoAnalysisResult;
    };
} | {
    uploading: {
        progress: bigint;
    };
} | {
    processing: null;
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        result: VideoAnalysisResult;
    };
} | {
    __kind__: "uploading";
    uploading: {
        progress: bigint;
    };
} | {
    __kind__: "processing";
    processing: null;
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: value.completed
    } : "uploading" in value ? {
        __kind__: "uploading",
        uploading: value.uploading
    } : "processing" in value ? {
        __kind__: "processing",
        processing: value.processing
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    wide: null;
} | {
    standard: null;
}): CameraModeType {
    return "wide" in value ? CameraModeType.wide : "standard" in value ? CameraModeType.standard : value;
}
async function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_VideoUpload>): Promise<Array<VideoUpload>> {
    return await Promise.all(value.map(async (x)=>await from_candid_VideoUpload_n11(_uploadFile, _downloadFile, x)));
}
function to_candid_CameraModeData_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CameraModeData): _CameraModeData {
    return to_candid_record_n24(_uploadFile, _downloadFile, value);
}
function to_candid_CameraModeType_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CameraModeType): _CameraModeType {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    wideSettings: WideSettings;
    fieldOfView: bigint;
    standardSettings: StandardSettings;
    activeMode: CameraModeType;
}): {
    wideSettings: _WideSettings;
    fieldOfView: bigint;
    standardSettings: _StandardSettings;
    activeMode: _CameraModeType;
} {
    return {
        wideSettings: value.wideSettings,
        fieldOfView: value.fieldOfView,
        standardSettings: value.standardSettings,
        activeMode: to_candid_CameraModeType_n8(_uploadFile, _downloadFile, value.activeMode)
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CameraModeType): {
    wide: null;
} | {
    standard: null;
} {
    return value == CameraModeType.wide ? {
        wide: null
    } : value == CameraModeType.standard ? {
        standard: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
